clc;
clear;
material = input('Material Name : ','s');
density = input('Density (kg/m^3): ');
width = input('Width (mm): ');
height = input('Height (mm): ');
thickness = input('Thickness (mm): ');
sea = input('SEA (kJ/kg): ');
area = width * height;
volume_mm3 = area * thickness;
volume_m3 = volume_mm3 / 1e9;
mass = density * volume_m3;
energy = sea * mass * 1000;
fprintf('\n=========================================\n');
fprintf('LAYER PROPERTIES\n');
fprintf('=========================================\n');
fprintf('Material : %s\n',material);
fprintf('Density : %.2f kg/m^3\n',density);
fprintf('Width : %.2f mm\n',width);
fprintf('Height : %.2f mm\n',height);
fprintf('Thickness : %.2f mm\n',thickness);
fprintf('Area : %.2f mm^2\n',area);
fprintf('Volume : %.8f m^3\n',volume_m3);
fprintf('Mass : %.4f kg\n',mass);
fprintf('SEA : %.2f kJ/kg\n',sea);
fprintf('Energy : %.2f J\n',energy);
fprintf('=========================================\n');
